specVersion: 0.0.1 # not used for now
org: story_zrunner_demo # required, usually this should be company name without space. Only alphanumeric characters and underscores are allowed.
kind: ethereum # chain name
network: sepolia # chain network
version: 1.0.0
name: story-zrunner-demo # required, not space or special chars allowed, must be consistent with the project folder name
githubRepo: "https://github.com/Zettablock/story-zrunner-demo"