// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

const TableNameCollection = "collection"

// Collection mapped from table <collection>
type Collection struct {
	BlockNumber           int64  `gorm:"column:block_number;not null" json:"block_number"`
	BlockTime             int64  `gorm:"column:block_time;not null" json:"block_time"`
	ID                    string `gorm:"column:id;primaryKey" json:"id"`
	AssetCount            int64  `gorm:"column:asset_count" json:"asset_count"`
	RaisedDisputeCount    int64  `gorm:"column:raised_dispute_count" json:"raised_dispute_count"`
	CancelledDisputeCount int64  `gorm:"column:cancelled_dispute_count" json:"cancelled_dispute_count"`
	ResolvedDisputeCount  int64  `gorm:"column:resolved_dispute_count" json:"resolved_dispute_count"`
	JudgedDisputeCount    int64  `gorm:"column:judged_dispute_count" json:"judged_dispute_count"`
	LicensesCount         int64  `gorm:"column:licenses_count" json:"licenses_count"`
}

// TableName Collection's table name
func (*Collection) TableName() string {
	return TableNameCollection
}
