// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

const TableNameLicenseTerm = "license_term"

// LicenseTerm mapped from table <license_term>
type LicenseTerm struct {
	BlockNumber     int64  `gorm:"column:block_number;not null" json:"block_number"`
	BlockTime       int64  `gorm:"column:block_time;not null" json:"block_time"`
	ID              string `gorm:"column:id;primaryKey" json:"id"`
	JSON            string `gorm:"column:json" json:"json"`
	LicenseTemplate string `gorm:"column:license_template" json:"license_template"`
}

// TableName LicenseTerm's table name
func (*LicenseTerm) TableName() string {
	return TableNameLicenseTerm
}
