// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

const TableNameTransaction = "transaction"

// Transaction mapped from table <transaction>
type Transaction struct {
	BlockNumber      int64  `gorm:"column:block_number;not null" json:"block_number"`
	BlockTime        int64  `gorm:"column:block_time;not null" json:"block_time"`
	ID               string `gorm:"column:id;primaryKey" json:"id"`
	TxHash           string `gorm:"column:tx_hash" json:"tx_hash"`
	TransactionIndex int32  `gorm:"column:transaction_index;not null" json:"transaction_index"`
	LogIndex         int32  `gorm:"column:log_index;not null" json:"log_index"`
	Initiator        string `gorm:"column:initiator" json:"initiator"`
	IPID             string `gorm:"column:ip_id" json:"ip_id"`
	ResourceID       string `gorm:"column:resource_id" json:"resource_id"`
	ResourceType     string `gorm:"column:resource_type" json:"resource_type"`
	ActionType       string `gorm:"column:action_type" json:"action_type"`
	CreatedAt        int64  `gorm:"column:created_at" json:"created_at"`
}

// TableName Transaction's table name
func (*Transaction) TableName() string {
	return TableNameTransaction
}
