name: ip-asset  # required, no space or special chars allowed, must be consistent with the pipeline folder name
source:
  startBlock: 1167044
eventHandlers: # multiple handlers
  - event: IPRegistered
    handler: HandlerIPRegistered
